import type { Metadata } from "next";
import { Poppins, Plus_Jakarta_Sans } from "next/font/google";

import "./globals.css";
import NavbarDesktop from "@/components/navbar";
import { navigationItems } from "@/data/navbarItems";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

const plusJakartaSans = Plus_Jakarta_Sans({
  variable: "--font-plus-jakarta-sans",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Oušťáci: Sdružení nezávislých kandidátů",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${poppins.variable} ${plusJakartaSans.variable} h-full antialiased`}
    >
      <body className="min-h-full max-w-screen overflow-x-hidden flex flex-col">
        <NavbarDesktop items={navigationItems} />
        {children}
      </body>
    </html>
  );
}
